# Generated by Django 4.1.5 on 2023-02-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cod',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='lib',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='user',
            field=models.IntegerField(default=1),
        ),
    ]
