# Generated by Django 4.1.5 on 2023-02-03 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblio', '0002_libro_cod_prestamo_lib_prestamo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='canStock',
        ),
    ]
