# Generated by Django 4.1.5 on 2023-02-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblio', '0003_remove_libro_canstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
