# Generated by Django 4.1.5 on 2023-02-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblio', '0004_prestamo_devuelto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='cod',
            new_name='inventario',
        ),
    ]
