# Generated by Django 4.1.5 on 2023-02-06 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBiblio', '0005_rename_cod_libro_inventario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='AñoIngreso',
            new_name='Ingreso',
        ),
    ]
